### PR TITLE
move to vuepress

### PR DESCRIPTION
**Pull request by andresribeiro**
@zhenghaoz i moved this documentation to [VuePress](https://vuepress.vuejs.org/)

it is still needed to configure GitHub Actions, which i think is something only you can do. the official docs for this are [here](https://vuepress.vuejs.org/guide/deploy.html#github-pages)

there is a basic search out of the box, but it could be improved using [Algolia DocSearch](https://docsearch.algolia.com/)

### CODE REVIEW

**Comment by zhenghaoz** [comment]
Hi @andresribeiro. Thank you so much. Could you add somee build steps in README.md :smile:

**Comment by andresribeiro** [comment]
> Hi @andresribeiro. Thank you so much. Could you add somee build steps in README.md smile

sorry 😅 i had forgotten about that

**Comment by andresribeiro** [comment]
done 🙂

**Comment by zhenghaoz** [comment]
Good jobs!

**Pull request merged**
